### ISSUE TITLE
R/C circuit details ?

### ISSUE THREAD

**Issue by sponnet** [ensonic/photon-waveout#3]
What are the the suggested values for the R/C circuit ?

**Comment by ensonic** [comment]
The cutoff frequency of the low-pass filter composed of the resistor and the capacitor is calculated by the formula:

```
F=1/2πRC
```

or

```
RC = 1/2πF
```

I have been using a 1 µF capacitor and a 47 Ω resistor. Applying these gives us a cut off at:

```
1/(2*3.1415*47*0.000001) = 3386.37525779 Hz
```

This is a bit low, a 10 nF capacitor and a larger resistor (2700 kΩ ) would be a better fit.
